### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by boogerstealer** [Tomato6966/Musicium#1]
Bot doesn’t even work

**Comment by Tomato6966** [comment]
It does? tell me what the problem is maybe i uploaded some wrong files

**Comment by Tomato6966** [comment]
It works, i just tested it, of course you need to replace all CUSTOM MADE EMOJIS (and their ids) Soon i will have a repository where you dont need to do this, but only when the Bot is FULLY Done! Hope that helps... cya

**Comment by Tomato6966** [comment]
Check out this Repository, which is the same exact Bot just with standard emojis, it works! I and others tested it!

https://github.com/Tomato6966/Music-Bot-with-Filter
