### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by mahdilupo** [Tomato6966/Musicium#101]
Autoplay just works when youre skipping the music. not when music ends

**Comment by XG-2580** [comment]
Just update the version of distube

**Comment by ojomangame** [comment]
I had the same problem, but i update the distube and other libraries and all works good!
Try this, it can really help you!
Sorry for my English im not american or same, im from Ukraine and can do mistakes)

**Comment by mahdilupo** [comment]
Thanks mate. its working now <3

‫‪ojomangame‬‏ ***@***.***‬‏> در تاریخ شنبه ۶ نوامبر ۲۰۲۱
ساعت ۱۳:۳۶ نوشت:‬
