### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by Bartek20** [Tomato6966/Musicium#104]
I don't know if I am doing something wrong or it has just not been implemented, but the option to enable https support for the dashboard does not work, will anyone help?

**Comment by Tomato6966** [comment]
it works, what is your error?

**Comment by Bartek20** [comment]
when enabling the bot, only the http version starts and when you try to connect to the website via HTTPS, the browser shows an error, this page cannot offer a secure connection

**Comment by Tomato6966** [comment]
did u do the ssls right?

**Comment by Bartek20** [comment]
I was able to solve the problem by watching the vps installation guide, I noticed that the code in the index.js file in the dashboard folder differs from that in the movie (there is no code with https support on github, only the http server is running)
