### ISSUE TITLE
[Enchancement] Tomato, can you try to add this to dashboard?

### ISSUE THREAD

**Issue by ojomangame** [Tomato6966/Musicium#105]
I saw in other music bot, on queue dashboard i have full control of playing music(stop, skip, pause, replay), and the field, where i can add the song to the queue, but in that bot wasnt autoplay, and i telling you that idea to add this thing to musicium, it will be the best!

**Comment by ojomangame** [comment]
And i so sorry for my english, im from ukraine)

**Comment by Tomato6966** [comment]
There are no buttons on the queue dashboard available.
