### ISSUE TITLE
Music error

### ISSUE THREAD

**Issue by Lcxd65** [Tomato6966/Musicium#106]
The bot crash when its playing a song and it says song ended. DONT close this issue if you dont explain me why or fix it

**Comment by WolfieBoyy** [comment]
Is your api key correct?
Are there any errors in the console?

**Comment by Lcxd65** [comment]
Everything is fine, rarely the bot stop playing music and say song ended

**Comment by Tomato6966** [comment]
This is because of your host, upgrade it 
allow the bot like 0.5gb or even more Ram
If it's over 100 Server syou def. need more then 1gb ram

Upgrade your Internet Speed and Latency
Upgrade your CPU

Don'T use repl.it without boosts, (Don't expect something free to work good as expected)

**Comment by Fernandopek211** [comment]
when
