### ISSUE TITLE
bot goes offline solution!!

### ISSUE THREAD

**Issue by mahdilupo** [Tomato6966/Musicium#111]
add this code to index.js

    const activities_list = [
        { type: 'WATCHING', message: 'status1' },
        { type: 'WATCHING', message: 'status2' },
        { type: 'LISTENING', message: 'status3' },
        { type: 'WATCHING', message: 'status4' }
    ];
    
    client.on('ready', () => {
        setInterval(() => {
            const index = Math.floor(Math.random() * (activities_list.length - 1) + 1);
    
            client.user.setActivity(activities_list[index].message, { type:     activities_list[index].type });
        }, 10000);
    });

you can change status 1.....4 

and remove  this code from /handlers/functions.js/ (line 760 to 762)

      client.user.setActivity(`${config.prefix}help | ${client.guilds.cache.size} Guilds | ${Math.ceil(client.users.cache.size/1000)}k Members`, {
        type: "PLAYING",
      });

then bot will change status every 10s and never goes offline

**Comment by Tomato6966** [comment]
This has nothing to do with the hosting of the bot

**Comment by testbot-github** [comment]
> This has nothing to do with the hosting of the bot

**THIS APPLIES TO REPLIT**
@Tomato6966 I think it is because if the bot is inactive [if the bot doesn't do anything] discord makes the bot offline, which happens to me, so the best way to fix it is to use the above way.
