### ISSUE TITLE
Dashboard Not Working

### ISSUE THREAD

**Issue by SharadS28N** [Tomato6966/Musicium#113]
I was using this project for my own personal bot and loved using dashboard. Now when I run my project it doesn't pop up the dashboard. I hosted it from replit

**Comment by Akshit1025** [comment]
> I was using this project for my own personal bot and loved using dashboard. Now when I run my project it doesn't pop up the dashboard. I hosted it from replit

can you please attach the logs that are coming in the console and a picture of web view inside of replit

**Comment by SharadS28N** [comment]
like everything is running on it just website didn't showed up so i again re cloned the project but it has some node issue

**Comment by Tomato6966** [comment]
Replit is not trustablr
