### ISSUE TITLE
Set activity status.

### ISSUE THREAD

**Issue by iamrahul24** [Tomato6966/Musicium#116]
if i simply copy paste client.user.setActivity("ok", { type: "PLAYING" }); in index,js it shows error. and if i copy paste it in ready.js it does not work either. 
I made sure bot gets offline but nothing happened.

**Comment by iamrahul24** [comment]
![image](https://user-images.githubusercontent.com/62786811/148494764-6e72d95a-dda6-4f72-b4b4-0489728f95f3.png)

**Comment by replBeluga3372** [comment]
handlers/functions.js
go to line 783 and then you can change the status
