### ISSUE TITLE
Can't run the bot in replit

### ISSUE THREAD

**Issue by Dani-Hacker** [Tomato6966/Musicium#122]
I imported the Musicium bot from github in replit and tried to run it in replit and I followed the youtube tutorial and filled all the necessary details but it ends up with the below error.
![image](https://user-images.githubusercontent.com/88134306/150737431-fe1fa669-b490-4b2f-8d19-074cc0b0eca8.png)
![image](https://user-images.githubusercontent.com/88134306/150737480-a4befe2d-ace3-433d-9f2f-d1b7af5bd3f5.png)
Please help me to fix this issue

**Comment by MondoPIX** [comment]
try `npm install --python="/usr/bin/python3.6"` or  `npm install --python=python2.7`

**Comment by shawn3308** [comment]
https://discord.com/channels/773668217163218944/854756037730500608/934868535551864902

**Comment by Dani-Hacker** [comment]
> `npm install --python="/usr/bin/python3.6"`

I tried this but it doesn't work and shows this error
![image](https://user-images.githubusercontent.com/88134306/150764248-f53fc935-be74-4ba3-94a7-4f024a727fce.png)

**Comment by Tomato6966** [comment]
u need nodejs v16.6

**Comment by Tomato6966** [comment]
just fork my replit

**Comment by daniel-jebarson** [comment]
thank you i forked the repo in replit and it worked
