### ISSUE TITLE
Lyrics not working

### ISSUE THREAD

**Issue by daniel-jebarson** [Tomato6966/Musicium#126]
I worked the replit repl and it all works fine but Lyrics is not working. Can someone help me to fix this issue

**Comment by MondoPIX** [comment]
it says why it doesn't work when you run the command

**Comment by Programador-jr** [comment]
> I worked the replit repl and it all works fine but Lyrics is not working. Can someone help me to fix this issue

The letters command is not working because ksoft that was responsible for delivering the API closed the services

**Comment by Deadpool7518** [comment]
> it says why it doesn't work when you run the command



> I worked the replit repl and it all works fine but Lyrics is not working. Can someone help me to fix this issue

Because of ksoft

**Comment by daniel-jebarson** [comment]
it doesn't say  anything the lyrics button is disabled

**Comment by MondoPIX** [comment]
try <yourprefix>ly or <yourprefix>lyrics

**Comment by ACGaming1508** [comment]
Lyrics are disabled due to KSoft.Si API stopped providing songs' lyrics

**Comment by daniel-jebarson** [comment]
oh ok
