### ISSUE TITLE
Some errors when starting the bot

### ISSUE THREAD

**Issue by BiskottoScriptato** [Tomato6966/Musicium#128]
When i start the bot there are some errors in the cmd:
(node:8308) DeprecationWarning: DisTubeOptions.youtubeDL is deprecated, set it to false and use `@distube/yt-dlp` instead.

**Comment by ACGaming1508** [comment]
> When i start the bot there are some errors in the cmd: (node:8308) DeprecationWarning: DisTubeOptions.youtubeDL is deprecated, set it to false and use `@distube/yt-dlp` instead.

As the error said, the youtubeDL option for Distube Client is deprecated. You just set it to `false` and use @distube/yt-dlp package instead(`npm i @distube/yt-dlp`)

**Comment by BiskottoScriptato** [comment]
> > When i start the bot there are some errors in the cmd: (node:8308) DeprecationWarning: DisTubeOptions.youtubeDL is deprecated, set it to false and use `@distube/yt-dlp` instead.
> 
> As the error said, the youtubeDL option for Distube Client is deprecated. You just set it to `false` and use @distube/yt-dlp package instead(`npm i @distube/yt-dlp`)

How do i do that
