### ISSUE TITLE
adding delay for user messages

### ISSUE THREAD

**Issue by mahdilupo** [Tomato6966/Musicium#136]
if(message.channel.id != textChannel.id) return;
        //Delete the message once it got sent into the channel, bot messages after 5 seconds, user messages instantly!
        if (message.author.id === client.user.id) {
          setTimeout(()=>{
            if (!message.deleted) {
              message.delete().catch((e) => {
                console.log(e)
              })
            }
          }, 3000)
        } else {
          if (!message.deleted) {
            message.delete().catch((e) => {
              console.log(e)
            })
          }
        }
    if(message.author.bot) return;
distubeEven.js line 1124 to 1139 @Tomato6966 @
I want to delete user messages after 3s like bot messages. What should I do?

**Comment by Tomato6966** [comment]
```js
    if(message.channel.id != textChannel.id) return;
    //Delete the message once it got sent into the channel, bot messages after 5 seconds, user messages instantly!
    if (message.author.id === client.user.id) {
      setTimeout(()=>{
        if (!message.deleted) {
          message.delete().catch((e) => {
            console.log(e)
          })
        }
      }, 3000)
    } else {
         setTimeout(()=>{
   if (!message.deleted) {
        message.delete().catch((e) => {
          console.log(e)
        })
      }
      }, 3000)
    }
if(message.author.bot) return;
```

**Comment by Tomato6966** [comment]
something like that
