### ISSUE TITLE
how can i add some more radio channels

### ISSUE THREAD

**Issue by freeh4ckcompany** [Tomato6966/Musicium#19]
how can i add some more radio channels

I want to add some indian radio channels too.. How can i do it?

**Comment by Tomato6966** [comment]
U need to get the radio station streamingurl

**Comment by freeh4ckcompany** [comment]
> U need to get the radio station streamingurl

and how can i get that?? like any website or??

**Comment by Tomato6966** [comment]
U can code a search cmd with the module radio-browser

Or check the html src code of websites

Just Google it takes a huge amount of time...
