### ISSUE TITLE
A random question.

### ISSUE THREAD

**Issue by biscuitfab** [Tomato6966/Musicium#26]
does it stay in the music channel 24/7?
i am not talking about hosting but like when you play music in a channel and leave the channel, does the bot still stay there?

**Comment by Tomato6966** [comment]
If u change the options right yes

**Comment by biscuitfab** [comment]
> If u change the options right yes

im sorry to ask this but how do you change the options such that it stays in a channel 24/7

**Comment by CASPERg267** [comment]
> > If u change the options right yes
> 
> im sorry to ask this but how do you change the options such that it stays in a channel 24/7?

make distube options into these
leaveonempty : false
leaveonfinish : false
leaveonstop : false
in index.js
and put a playlist into the loop and it ll stay in voice channel for 24/7

**Comment by biscuitfab** [comment]
> > > If u change the options right yes
> > 
> > 
> > im sorry to ask this but how do you change the options such that it stays in a channel 24/7?
> 
> make distube options into these
> leaveonempty : false
> leaveonfinish : false
> leaveonstop : false
> in index.js
> and put a playlist into the loop and it ll stay in voice channel for 24/7

thank you , the bot is amazing
