### ISSUE TITLE
Usercount issue

### ISSUE THREAD

**Issue by Beri78** [Tomato6966/Musicium#27]
Here is the code: it just shows k User | 2 server // the server one works, but the user count is not.
![user](https://user-images.githubusercontent.com/84451132/118961167-4fb40c80-b964-11eb-9eba-9a51c5ac61de.PNG)

 
 for (let i = 0; i < guilds.length; i++) {
                usercount += Number(client.guilds.cache.get(guilds[i]).memberCount);
            }
            usercount *= 10;
            usercount = usercount.toString().slice(3)
            stateswitch = !stateswitch; //change state
            if (stateswitch) client.user.setActivity(`${config.prefix}help | musicium.eu`, {
                type: "PLAYING"
            });
            else client.user.setActivity(`${usercount}k User | ${client.guilds.cache.size} Server`, {
                type: "PLAYING"
            });
        }, 5000); //5 second delay

**Comment by JacProsser** [comment]
just change it to this:
```
   client.on("ready", () => {
        setInterval(() => {
            stateswitch = !stateswitch; //change state
            if (stateswitch) client.user.setActivity(`${config.prefix}help | musicium.eu`, {
                type: "PLAYING"
            });
            else client.user.setActivity(`${client.users.cache.size} User | ${client.guilds.cache.size} Server`, {
                type: "PLAYING"
            });
        }, 5000); //5 second delay
```

**Comment by Beri78** [comment]
Ty it worked!

**Comment by JacProsser** [comment]
you're welcome
