### ISSUE TITLE
1 Typo and 1 Bug

### ISSUE THREAD

**Issue by Positive2022** [Tomato6966/Musicium#31]
Typo:
In line 219 of radiostations.json, there is an extra `-`
![Screenshot_101](https://user-images.githubusercontent.com/70850451/120923712-94be9980-c6ed-11eb-8345-65a130d7339d.png)
It should be:
"Radio-Ayeneh http://83.251.229.97/streampath1.mp3/;",
so the embed does not shows the link of radio directly.

Bug:
The length of requested radio exceeds 2048 chracters. Maybe not include links in requested radio stations. :feelsInvisibleman:

**Comment by Tomato6966** [comment]
U can easily change it
