### ISSUE TITLE
are source can play Soundcloud or mp3?

### ISSUE THREAD

**Issue by GeoXTen** [Tomato6966/Musicium#37]

**Comment by Tomato6966** [comment]
yes

**Comment by GeoXTen** [comment]
![image](https://user-images.githubusercontent.com/46945867/131359691-c654285c-534f-426f-8965-f5d5c0167146.png)
ok could you help with this?

**Comment by GeoXTen** [comment]
im using link soundcloud and getting error

**Comment by Tomato6966** [comment]
ur soundcloud api key is blocked

**Comment by GeoXTen** [comment]
> ur soundcloud api key is blocked

where should i change api soundcloud/youtube, also mp3 url not valid for me

**Comment by Tomato6966** [comment]
there where you defined it in your .evn

**Comment by GeoXTen** [comment]
![image](https://user-images.githubusercontent.com/46945867/131368127-4c1a4767-82d0-4af1-a77c-b0eebaeb5707.png)
this?
