### ISSUE TITLE
activity status

### ISSUE THREAD

**Issue by GeoXTen** [Tomato6966/Musicium#47]
![image](https://user-images.githubusercontent.com/46945867/132986431-bd9cc274-2275-4f4b-8de8-0f583127a7c7.png)

i did change ``client.user.setActivity("ok", { type: "PLAYING" });`` but they still there where i can change them?

**Comment by Tomato6966** [comment]
check index.js...

**Comment by GeoXTen** [comment]
i did check and change them but still...

**Comment by Tomato6966** [comment]
then wait until the bot is offline then start again, this is a discord visuality bug
