### ISSUE TITLE
ReferenceError: volume is not defined

### ISSUE THREAD

**Issue by x7s** [Tomato6966/Musicium#49]
https://github.com/Tomato6966/Musicium/blob/87cecd18c478a60f70c7c52a98f77fee8d896a37/commands/Queue/shuffle.js#L78

https://github.com/Tomato6966/Musicium/blob/87cecd18c478a60f70c7c52a98f77fee8d896a37/slashCommands/Queue/shuffle.js#L75
I guess the mistake was inadvertently made here

**Comment by Tomato6966** [comment]
yea thx
