### ISSUE TITLE
Can u make a toggle pruning command?

### ISSUE THREAD

**Issue by iamnoob6969** [Tomato6966/Musicium#58]

**Comment by TheCoolOne123** [comment]
Some more info would be nice \:P

**Comment by iamnoob6969** [comment]
> Some more info would be nice :P
https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/blob/main/commands/%E2%9A%99%EF%B8%8F%20Settings/togglepruning.js

**Comment by Tomato6966** [comment]
not wanted for the musicium bot! You can make it yourself not hard...
