### ISSUE TITLE
Possible to use this on VS code?

### ISSUE THREAD

**Issue by iGetUploaded** [Tomato6966/Musicium#61]
Is there any way I can put this onto vs code? I've tried but I'm getting weird errors?

![image](https://user-images.githubusercontent.com/54633753/134078169-6e525a51-5a9b-4b47-9e4e-a2755be855cc.png)

**Comment by Tomato6966** [comment]
have git python3.9 and nodejs v16.6+ on your machine... vs code is just a text editor u need to install the software first
