### ISSUE TITLE
how to make lyrics work?

### ISSUE THREAD

**Issue by amanvenkat** [Tomato6966/Musicium#64]

**Comment by mrhacker09-cobra** [comment]
Ksoft API has been stopped for a particular time so when Ksoft API starts to work the lyrics will be available for everyone. SO please wait

**Comment by FauziFerdiansyah** [comment]
Can change to other API Lyric?

**Comment by Tomato6966** [comment]
Due to legal reasons ksoft api is closed and any other lyrics grabbing software could cause problems for you
