### ISSUE TITLE
Afk command for the bot

### ISSUE THREAD

**Issue by amanvenkat** [Tomato6966/Musicium#65]
How can I keep the bot in channel 24/7 without making it leave.

**Comment by TOXIC6163** [comment]
> How can I keep the bot in channel 24/7 without making it leave.

**THERE IS NO AFK COMMAND ONLY WAY TI MAKE BOT STAY IN THE CHANNEL 24/7 IS BY ONLY ENABLING AUTOPLAY**

**Comment by iniznet** [comment]
You can do it in index.js
https://github.com/Tomato6966/Musicium/blob/4a9be612bec06bf06ebb2dee02569ad326ffdcd3/index.js#L64-L68
