### ISSUE TITLE
Not able to prevent bot from leaving vc

### ISSUE THREAD

**Issue by TahaGorme** [Tomato6966/Musicium#66]
i dont want the bot to leave vc after song ends. it should stay in vc 24/7 . how to do i????????

**Comment by TOXIC6163** [comment]
> i dont want the bot to leave vc after song ends. it should stay in vc 24/7 . how to do i????????

**BY ENABLING AUTOPLAY**

**Comment by TahaGorme** [comment]
@TOXIC6163  not working

**Comment by TahaGorme** [comment]
it leaves even if autoplay is off or on

**Comment by iniznet** [comment]
Check index.js
https://github.com/Tomato6966/Musicium/blob/4a9be612bec06bf06ebb2dee02569ad326ffdcd3/index.js#L66-L68

**Comment by junny2233** [comment]
> it leaves even if autoplay is on or off
> 
> 

Inside index.js line 64 you can see this options
  emitNewSongOnly: false,
  leaveOnEmpty: true, <-- CHANGE THIS TO FALSE
  leaveOnFinish: true, <-- CHANGE THIS TO FALSE
  leaveOnStop: true, <-- CHANGE THIS TO FALSE

**Comment by TahaGorme** [comment]
@junny2233  what should be value of emitnewsongony ??
