### ISSUE TITLE
Loop command song cannot function well

### ISSUE THREAD

**Issue by ShiroChan8520** [Tomato6966/Musicium#67]
When I do loop song command the bot leave the voice channel after song ended , it sent a message as there is no song left. Also the loop queue is work fine. So what is the problem actually?

**Comment by ShiroChan8520** [comment]
It shown the :approved: song in the line of the show list there and it doesn't loop the song

**Comment by iniznet** [comment]
It seems so, I tried and it's only able to repeat a song when the queue has two or more songs.

**Comment by ShiroChan8520** [comment]
Yeah , also the slash command doesn't work as well

**Comment by ShiroChan8520** [comment]
So tomato can you guide us how to fix it?

**Comment by Tomato6966** [comment]
this is a bug by DISTUBE I will contact the package dev
