### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by L4KILL** [Tomato6966/Musicium#70]
on the console it keeps giving this error after a few minutes.
<==>  [Thu Sep 23 2021 22:29:03]  <==>  Shard #0 Reconnecting  <==> 
e na hora que ínicio o bot também da esse erro: 
[Thu Sep 23 2021 23:04:14]  <==>  Shard #0 Ready  <==> 
what do I do?

**Comment by Tomato6966** [comment]
Fix your internet
