### ISSUE TITLE
Bot Crashes everytimewhen using the queue command after reacting to the NP  ( ? ) button

### ISSUE THREAD

**Issue by Host911** [Tomato6966/Musicium#74]
Bot Crashes when using the queue command after reacting to the NP  ( ? ) button

**Comment by junny2233** [comment]
> Bot Crashes when using the queue command after reacting to the NP  ( ? ) button
> 
> 

Do you have any error in console/shell?

**Comment by Host911** [comment]
This is what happens when i click the red question button, it crashes instantly the bot goes down

/home/ubuntu/KYL-Bot/include/play.js:83
    queue.connection.on("disconnect", () => message.client.queue.delete(message.guild.id));   
                     ^

TypeError: Cannot read properties of null (reading 'on')
    at play (/home/ubuntu/KYL-Bot/include/play.js:83:22)
    at Object.execute (/home/ubuntu/KYL-Bot/Music/play.js:184:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ubuntu@ip-172-31-28-193:~/KYL-Bot$ /home/ubuntu/KYL-Bot/include/play.js:83

**Comment by TheCoolOne123** [comment]
@Host911 
Are you using a modified version of the code? Or is it the exact same?
Stopping doesn't crash mine:
![image](https://user-images.githubusercontent.com/25939526/135509777-325dbda2-b931-4e29-b3d1-d191f4637769.png)
![image](https://user-images.githubusercontent.com/25939526/135509805-05ece8ee-001c-4294-b751-e65c8fd4f3d9.png)

**Comment by Host911** [comment]
The exact same code

**Comment by Tomato6966** [comment]
Ignore it if it doesnt work make sure to use nodejs v16.6+ and latest npm modules.

Or upgrade your vps
