### ISSUE TITLE
The Play/Pause button only pauses the music, but don't resume it

### ISSUE THREAD

**Issue by Host911** [Tomato6966/Musicium#75]
The Play/Pause button only pauses the music, but don't resume it

Test : 
- play a song
- Click the pause button
- Notice that the music stopped
- Reclick the play/pause button and notice it doesn't resume

**Comment by TheCoolOne123** [comment]
I cannot reproduce this issue. Running NodeJS 16

**Comment by SubDivisionRP** [comment]
Same for me

**Comment by Tomato6966** [comment]
This is an issue on distube.js.org

This is not related to the Musicium Bot Source, rather to your engine and nodejs version

if you could grant us node -v
as well as python --version and npm ls ffmpeg-static

we could help you more

or check out: 
![image](https://user-images.githubusercontent.com/68145571/135764843-0546965b-4089-43d9-af69-50d1ae598c85.png)
