### ISSUE TITLE
Dashboard not showing up in the browser

### ISSUE THREAD

**Issue by TariqDaCoder** [Tomato6966/Musicium#77]
This is what I get when I run the bot,
`[http://bot.tariq.gg]: HTTP-Website running on 80 port.`
but when I go to my site I get this
`This site can’t be reachedbot.tariq.gg took too long to respond.`
I have bot.tariq.gg pointed at the server where the bot is located
![vlcsnap-2021-09-12-09h12m00s397](https://user-images.githubusercontent.com/48069210/135745026-8cf678e4-84fc-4fdc-abb0-a6a908afc87c.png)
![Capture](https://user-images.githubusercontent.com/48069210/135745027-75745b10-60d4-4d99-9d17-507b8ffe1666.PNG)
.

**Comment by junny2233** [comment]
> This is what I get when I run the bot, `[http://bot.tariq.gg]: HTTP-Website running on 80 port.` but when I go to my site I get this `This site can’t be reachedbot.tariq.gg took too long to respond.` I have bot.tariq.gg pointed at the server where the bot is located ![vlcsnap-2021-09-12-09h12m00s397](https://user-images.githubusercontent.com/48069210/135745026-8cf678e4-84fc-4fdc-abb0-a6a908afc87c.png) ![Capture](https://user-images.githubusercontent.com/48069210/135745027-75745b10-60d4-4d99-9d17-507b8ffe1666.PNG) .

seems like your ports are not open properly or something with your netowrk. 

are you using a vpn and/or vps? if now what it is?

**Comment by Tomato6966** [comment]
Have u liked ur Website to the host via DNS?
It might take up to 48hours to do so.

Try to connect to the dashboard using the ip of ur host

**Comment by Tomato6966** [comment]
U can take a look at the src everything is just fine

**Comment by TariqDaCoder** [comment]
Thanks for the replay guys. I was able to get it fix by typing the following
`sudo ufw enable
sudo ufw allow 80`

**Comment by Tomato6966** [comment]
normally port 80 is open on any vps, so that didn't cam into my mind, sorry but glad you fixxed it!
