### ISSUE TITLE
Multiple Resolves

### ISSUE THREAD

**Issue by AceKiller250** [Tomato6966/Musicium#81]
Almost everysong I play gets the error 

`[antiCrash] :: Multiple Resolves`

How do I fix this?

**Comment by junny2233** [comment]
can you please provide more information like console screenshot

**Comment by AceKiller250** [comment]
@junny2233 I think I have filled out all of the info I didnt fill out the youtube cookie because I dont know what it is or how to get it, here is a screenshot of my console
![222](https://user-images.githubusercontent.com/74756559/135969261-c036a8e5-71c8-4b41-809b-86d0a86051b1.PNG)

**Comment by Tomato6966** [comment]
This is just an error from @discordjs/voice when destroying a connection, ignore that! Everything with [antiCrash] can be ignore, unless you see the error with it
