### ISSUE TITLE
Bot crash after searching music

### ISSUE THREAD

**Issue by LudovicoSforza** [Tomato6966/Musicium#82]
`An error encountered: PlayingError: Error: Cannot find module '@discordjs/opus'
Require stack:
- /home/container/node_modules/prism-media/src/util/loader.js
- /home/container/node_modules/prism-media/src/opus/Opus.js
- /home/container/node_modules/prism-media/src/opus/index.js
- /home/container/node_modules/prism-media/src/index.js
- /home/container/node_modules/@discordjs/voice/dist/audio/TransformerGraph.js
- /home/container/node_modules/@discordjs/voice/dist/audio/AudioResource.js
- /home/container/node_modules/@discordjs/voice/dist/audio/index.js
- /home/container/node_modules/@discordjs/voice/dist/index.js
- /home/container/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/container/node_modules/prism-media/src/util/loader.js
- /home/container/node_modules/prism-media/src/opus/Opus.js
- /home/container/node_modules/prism-media/src/opus/index.js
- /home/container/node_modules/prism-media/src/index.js
- /home/container/node_modules/@discordjs/voice/dist/audio/TransformerGraph.js
- /home/container/node_modules/@discordjs/voice/dist/audio/AudioResource.js
- /home/container/node_modules/@discordjs/voice/dist/audio/index.js
- /home/container/node_modules/@discordjs/voice/dist/index.js
- /home/container/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/container/node_modules/prism-media/src/util/loader.js
- /home/container/node_modules/prism-media/src/opus/Opus.js
- /home/container/node_modules/prism-media/src/opus/index.js
- /home/container/node_modules/prism-media/src/index.js
- /home/container/node_modules/@discordjs/voice/dist/audio/TransformerGraph.js
- /home/container/node_modules/@discordjs/voice/dist/audio/AudioResource.js
- /home/container/node_modules/@discordjs/voice/dist/audio/index.js
- /home/container/node_modules/@discordjs/voice/dist/index.js
- /home/container/index.js
ID: XbGs_qK2PQA
Name: Eminem - Rap God (Explicit)
An error encountered: PlayingError: Cannot destructure property 'duration' of 'queue.songs[0]' as it is undefined.
`

im curently using main-without-Dashboard branch 
How do i fix it?

**Comment by TOXIC6163** [comment]
**U NEED TO INSTALL THOSE MODULES OR U CAN'T RUN BOT / MUSIC**
_SO INSTALL MODULES FIRST BY_ `npm i ` or `npm i @discordjs/opus`

**Comment by Tomato6966** [comment]
npm i @discordjs/opus
